#!/usr/bin/env bash
#
# 构建 Arch Linux 安装包（.pkg.tar.zst）
#
# Compose Desktop 的 nativeDistributions 只支持 deb/rpm/appimage，
# 因此这里先产出可运行的发行目录（createReleaseDistributable），
# 再按 pacman 包结构（.PKGINFO + .MTREE + bsdtar --zstd）手工组装。
#
# 用法：
#   scripts/build-arch-package.sh              # 先编译再打包
#   scripts/build-arch-package.sh --skip-build # 跳过编译，复用已有发行目录
#
# 依赖：JDK 21+、bsdtar（libarchive，需带 libzstd）
#
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

readonly PKG_NAME="qadb"
readonly PKG_REL="1"
readonly PKG_ARCH="x86_64"
readonly PKG_DESC="An open-source, cross-platform, modern ADB desktop debugging tool"
readonly PKG_URL="https://ludoven.github.io/QADB/"

readonly BINARIES_DIR="$PROJECT_ROOT/composeApp/build/compose/binaries/main-release"
readonly APP_ROOT="$BINARIES_DIR/app"
readonly OUT_DIR="$BINARIES_DIR/arch"
readonly ICON_FILE="$PROJECT_ROOT/composeApp/src/desktopMain/composeResources/drawable/ic_logo.png"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m错误:\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
    sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
}

skip_build="false"
for arg in "$@"; do
    case "$arg" in
        --skip-build) skip_build="true" ;;
        -h|--help) usage; exit 0 ;;
        *) fail "未知参数：$arg（可用参数：--skip-build）" ;;
    esac
done

# ---- 前置检查 ----------------------------------------------------------------

command -v bsdtar >/dev/null 2>&1 || fail "缺少 bsdtar，请先安装 libarchive"
bsdtar --version | grep -q "libzstd" || fail "当前 bsdtar 未链接 libzstd，无法生成 .pkg.tar.zst"
[ -f "$ICON_FILE" ] || fail "缺少图标文件：$ICON_FILE"

# ---- 读取版本号 --------------------------------------------------------------

app_version="$(sed -n 's/.*val appVersion = "\([^"]*\)".*/\1/p' \
    "$PROJECT_ROOT/composeApp/build.gradle.kts" | head -n 1)"
[ -n "$app_version" ] || fail "无法从 composeApp/build.gradle.kts 读取 appVersion"

# ---- 编译发行目录 ------------------------------------------------------------

if [ "$skip_build" = "false" ]; then
    log "编译可运行发行目录 :composeApp:createReleaseDistributable"
    ( cd "$PROJECT_ROOT" && ./gradlew --console=plain :composeApp:createReleaseDistributable )
else
    log "跳过编译，复用已有发行目录"
fi

app_dir="$(find "$APP_ROOT" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | head -n 1)"
[ -n "$app_dir" ] || fail "未找到发行目录：$APP_ROOT/<AppName>，请先执行不带 --skip-build 的构建"

launcher="$(find "$app_dir/bin" -mindepth 1 -maxdepth 1 -type f 2>/dev/null | head -n 1)"
[ -n "$launcher" ] || fail "发行目录中未找到启动脚本：$app_dir/bin"
launcher_name="$(basename "$launcher")"

log "应用版本 $app_version，发行目录 $(basename "$app_dir")，启动器 $launcher_name"

# ---- 组装包文件树 ------------------------------------------------------------

staging="$OUT_DIR/staging"
log "组装包文件树 $staging"
rm -rf "$staging"
mkdir -p "$staging/opt/QADB" \
         "$staging/usr/bin" \
         "$staging/usr/share/applications" \
         "$staging/usr/share/pixmaps"

cp -a "$app_dir/." "$staging/opt/QADB/"

ln -s "/opt/QADB/bin/$launcher_name" "$staging/usr/bin/qadb"
cp "$ICON_FILE" "$staging/usr/share/pixmaps/qadb.png"

cat > "$staging/usr/share/applications/qadb.desktop" <<'EOF'
[Desktop Entry]
Name=QADB
Comment=An open-source, cross-platform, modern ADB desktop debugging tool
Exec=/usr/bin/qadb
Icon=qadb
Terminal=false
Type=Application
Categories=Development;Utility;
EOF

# ---- 包元数据 ----------------------------------------------------------------

pkg_size="$(du -sb "$staging" | awk '{print $1}')"
cat > "$staging/.PKGINFO" <<EOF
# Generated by QADB build script
pkgname = $PKG_NAME
pkgbase = $PKG_NAME
pkgver = $app_version-$PKG_REL
pkgdesc = $PKG_DESC
url = $PKG_URL
builddate = $(date -u +%s)
packager = QADB Release <ludoven>
size = $pkg_size
arch = $PKG_ARCH
license = MIT
EOF

# pacman 要求归档内的路径不带 "./" 前缀（否则读不到 .PKGINFO），
# 而 .MTREE 内的路径需要带 "./"（与官方 makepkg 产物一致）。
# 同时借助 fakeroot 让归档内的 uid/gid 记录为 root，与官方包一致。
pkg_tool=()
if command -v fakeroot >/dev/null 2>&1; then
    pkg_tool=(fakeroot --)
else
    printf '\033[1;33m警告:\033[0m 未找到 fakeroot，包内文件所有者将记录为当前用户\n' >&2
fi

log "生成文件校验清单 .MTREE"
# 用 find 显式列出条目（排除 .MTREE 自身），路径保留 "./" 前缀，与 makepkg 产物一致
( cd "$staging" && export LANG=C && \
    find . -mindepth 1 ! -name .MTREE -print0 | \
    "${pkg_tool[@]}" bsdtar --no-fflags --null -T - -czf .MTREE --format=mtree \
        --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' )

# ---- 打包 --------------------------------------------------------------------

mkdir -p "$OUT_DIR"
pkg_path="$OUT_DIR/$PKG_NAME-$app_version-$PKG_REL-$PKG_ARCH.pkg.tar.zst"
rm -f "$pkg_path"

log "生成 $pkg_path"
# 1. 用绝对路径，避免在 staging 目录内被相对解析
# 2. 显式列出元数据文件并用 glob 展开顶层目录，保证归档根为 .PKGINFO / .MTREE / usr / opt
( cd "$staging" && "${pkg_tool[@]}" bsdtar --no-fflags --zstd -cf "$pkg_path" \
    .PKGINFO .MTREE * )

rm -rf "$staging"

log "完成"
ls -lh "$pkg_path"
